In [ ]:
import pandas as pd
import requests
from price_cache_manager import get_clean_price_df
#obtain the component for S&P 500
def get_sp500_tickers():
    url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"

    headers = {
        "User-Agent": "Mozilla/5.0"
    }

    response = requests.get(url, headers=headers)
    response.raise_for_status()

    tables = pd.read_html(response.text)
    table = tables[0]

    tickers = table["Symbol"].tolist()

    # 🔥 yfinance 格式修复
    tickers = [t.replace(".", "-") for t in tickers]

    return tickers
sp500_tickers = get_sp500_tickers()

print(len(sp500_tickers))
sp500_tickers[:10]

503

/var/folders/l6/qn_dxw8j00x3g2ft_6s4sz4w0000gn/T/ipykernel_3037/4063061612.py:15: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(response.text)

['MMM', 'AOS', 'ABT', 'ABBV', 'ACN', 'ADBE', 'AMD', 'AES', 'AFL', 'A']

In [5]:
test_tickers = sp500_tickers[:10]

df_test = get_clean_price_df(test_tickers)

df_test.head()

Processing MMM...
Processing AOS...
Processing ABT...
Processing ABBV...
Processing ACN...
Processing ADBE...
Processing AMD...
Processing AES...
Processing AFL...
Processing A...

,date,ticker,open,high,low,close,adj_close,volume
0,2000-01-03,A,46.963894,47.075713,40.180220,42.938419,42.938419,4674353
1,2000-01-04,A,40.627500,41.074778,38.614762,39.658405,39.658405,4765083
2,2000-01-05,A,39.509313,39.658406,35.968387,37.198391,37.198391,5758642
3,2000-01-06,A,36.751110,36.974749,34.663825,35.782013,35.782013,2534434
4,2000-01-07,A,35.222912,39.322934,35.185641,38.763840,38.763840,2819626

In [ ]:
from tqdm import tqdm
#use cache to store the data
def download_sp500_in_batches(tickers, batch_size=20):
    all_df = []

    for i in tqdm(range(0, len(tickers), batch_size)):
        batch = tickers[i:i+batch_size]

        try:
            df_batch = get_clean_price_df(batch)
            all_df.append(df_batch)
        except Exception as e:
            print(f"Error in batch {i}: {e}")

    df_all = pd.concat(all_df, ignore_index=True)
    return df_all

In [7]:
df_sp500 = download_sp500_in_batches(sp500_tickers, batch_size=20)

  0%|          | 0/26 [00:00<?, ?it/s]

Processing MMM...
Processing AOS...
Processing ABT...
Processing ABBV...
Processing ACN...
Processing ADBE...
Processing AMD...
Processing AES...
Processing AFL...
Processing A...
Processing APD...
Processing ABNB...
Processing AKAM...
Processing ALB...
Processing ARE...
Processing ALGN...
Processing ALLE...
Processing LNT...
Processing ALL...
Processing GOOGL...

  4%|▍         | 1/26 [00:06<02:48,  6.74s/it]

Processing GOOG...
Processing MO...
Processing AMZN...
Processing AMCR...
Processing AEE...
Processing AEP...
Processing AXP...
Processing AIG...
Processing AMT...
Processing AWK...
Processing AMP...
Processing AME...
Processing AMGN...
Processing APH...
Processing ADI...
Processing AON...
Processing APA...
Processing APO...
Processing AAPL...
Processing AMAT...

  8%|▊         | 2/26 [00:17<03:37,  9.05s/it]

Processing APP...
Processing APTV...
Processing ACGL...
Processing ADM...
Processing ARES...
Processing ANET...
Processing AJG...
Processing AIZ...
Processing T...
Processing ATO...
Processing ADSK...
Processing ADP...
Processing AZO...
Processing AVB...
Processing AVY...
Processing AXON...
Processing BKR...
Processing BALL...
Processing BAC...
Processing BAX...

 12%|█▏        | 3/26 [00:29<04:01, 10.49s/it]

Processing BDX...
Processing BRK-B...
Processing BBY...
Processing TECH...
Processing BIIB...
Processing BLK...
Processing BX...
Processing XYZ...
Processing BK...
Processing BA...
Processing BKNG...
Processing BSX...
Processing BMY...
Processing AVGO...
Processing BR...
Processing BRO...
Processing BF-B...
Processing BLDR...
Processing BG...
Processing BXP...

 15%|█▌        | 4/26 [00:44<04:26, 12.13s/it]

Processing CHRW...
Processing CDNS...
Processing CPT...
Processing CPB...
Processing COF...
Processing CAH...
Processing CCL...
Processing CARR...
Processing CVNA...
Processing CASY...
Processing CAT...
Processing CBOE...
Processing CBRE...
Processing CDW...
Processing COR...
Processing CNC...
Processing CNP...
Processing CF...
Processing CRL...
Processing SCHW...

 19%|█▉        | 5/26 [00:55<04:04, 11.66s/it]

Processing CHTR...
Processing CVX...
Processing CMG...
Processing CB...
Processing CHD...
Processing CIEN...
Processing CI...
Processing CINF...
Processing CTAS...
Processing CSCO...
Processing C...
Processing CFG...
Processing CLX...
Processing CME...
Processing CMS...
Processing KO...
Processing CTSH...
Processing COHR...
Processing COIN...
Processing CL...

 23%|██▎       | 6/26 [01:05<03:45, 11.29s/it]

Processing CMCSA...
Processing FIX...
Processing CAG...
Processing COP...
Processing ED...
Processing STZ...
Processing CEG...
Processing COO...
Processing CPRT...
Processing GLW...
Processing CPAY...
Processing CTVA...
Processing CSGP...
Processing COST...
Processing CTRA...
Processing CRH...
Processing CRWD...
Processing CCI...
Processing CSX...
Processing CMI...

 27%|██▋       | 7/26 [01:16<03:29, 11.02s/it]

Processing CVS...
Processing DHR...
Processing DRI...
Processing DDOG...
Processing DVA...
Processing DECK...
Processing DE...
Processing DELL...
Processing DAL...
Processing DVN...
Processing DXCM...
Processing FANG...
Processing DLR...
Processing DG...
Processing DLTR...
Processing D...
Processing DPZ...
Processing DASH...
Processing DOV...
Processing DOW...

 31%|███       | 8/26 [01:25<03:10, 10.58s/it]

Processing DHI...
Processing DTE...
Processing DUK...
Processing DD...
Processing ETN...
Processing EBAY...
Processing SATS...
Processing ECL...
Processing EIX...
Processing EW...
Processing EA...
Processing ELV...
Processing EME...
Processing EMR...
Processing ETR...
Processing EOG...
Processing EPAM...
Processing EQT...
Processing EFX...
Processing EQIX...

 35%|███▍      | 9/26 [01:42<03:32, 12.52s/it]

Processing EQR...
Processing ERIE...
Processing ESS...
Processing EL...
Processing EG...
Processing EVRG...
Processing ES...
Processing EXC...
Processing EXE...
Processing EXPE...
Processing EXPD...
Processing EXR...
Processing XOM...
Processing FFIV...
Processing FDS...
Processing FICO...
Processing FAST...
Processing FRT...
Processing FDX...
Processing FIS...

 38%|███▊      | 10/26 [01:53<03:14, 12.13s/it]

Processing FITB...
Processing FSLR...
Processing FE...
Processing FISV...
Processing F...
Processing FTNT...
Processing FTV...
Processing FOXA...
Processing FOX...
Processing BEN...
Processing FCX...
Processing GRMN...
Processing IT...
Processing GE...
Processing GEHC...
Processing GEV...
Processing GEN...
Processing GNRC...
Processing GD...
Processing GIS...

 42%|████▏     | 11/26 [02:04<02:54, 11.63s/it]

Processing GM...
Processing GPC...
Processing GILD...
Processing GPN...
Processing GL...
Processing GDDY...
Processing GS...
Processing HAL...
Processing HIG...
Processing HAS...
Processing HCA...
Processing DOC...
Processing HSIC...
Processing HSY...
Processing HPE...
Processing HLT...
Processing HD...
Processing HON...
Processing HRL...
Processing HST...

 46%|████▌     | 12/26 [02:15<02:39, 11.41s/it]

Processing HWM...
Processing HPQ...
Processing HUBB...
Processing HUM...
Processing HBAN...
Processing HII...
Processing IBM...
Processing IEX...
Processing IDXX...
Processing ITW...
Processing INCY...
Processing IR...
Processing PODD...
Processing INTC...
Processing IBKR...
Processing ICE...
Processing IFF...
Processing IP...
Processing INTU...
Processing ISRG...

 50%|█████     | 13/26 [02:26<02:26, 11.23s/it]

Processing IVZ...
Processing INVH...
Processing IQV...
Processing IRM...
Processing JBHT...
Processing JBL...
Processing JKHY...
Processing J...
Processing JNJ...
Processing JCI...
Processing JPM...
Processing KVUE...
Processing KDP...
Processing KEY...
Processing KEYS...
Processing KMB...
Processing KIM...
Processing KMI...
Processing KKR...
Processing KLAC...

 54%|█████▍    | 14/26 [02:36<02:11, 10.94s/it]

Processing KHC...
Processing KR...
Processing LHX...
Processing LH...
Processing LRCX...
Processing LVS...
Processing LDOS...
Processing LEN...
Processing LII...
Processing LLY...
Processing LIN...
Processing LYV...
Processing LMT...
Processing L...
Processing LOW...
Processing LULU...
Processing LITE...
Processing LYB...
Processing MTB...
Processing MPC...

 58%|█████▊    | 15/26 [02:47<02:00, 10.93s/it]

Processing MAR...
Processing MRSH...
Processing MLM...
Processing MAS...
Processing MA...
Processing MKC...
Processing MCD...
Processing MCK...
Processing MDT...
Processing MRK...
Processing META...
Processing MET...
Processing MTD...
Processing MGM...
Processing MCHP...
Processing MU...
Processing MSFT...
Processing MAA...
Processing MRNA...
Processing TAP...

 62%|██████▏   | 16/26 [03:02<02:02, 12.25s/it]

Processing MDLZ...
Processing MPWR...
Processing MNST...
Processing MCO...
Processing MS...
Processing MOS...
Processing MSI...
Processing MSCI...
Processing NDAQ...
Processing NTAP...
Processing NFLX...
Processing NEM...
Processing NWSA...
Processing NWS...
Processing NEE...
Processing NKE...
Processing NI...
Processing NDSN...
Processing NSC...
Processing NTRS...

 65%|██████▌   | 17/26 [03:12<01:45, 11.70s/it]

Processing NOC...
Processing NCLH...
Processing NRG...
Processing NUE...
Processing NVDA...
Processing NVR...
Processing NXPI...
Processing ORLY...
Processing OXY...
Processing ODFL...
Processing OMC...
Processing ON...
Processing OKE...
Processing ORCL...
Processing OTIS...
Processing PCAR...
Processing PKG...
Processing PLTR...
Processing PANW...
Processing PSKY...

 69%|██████▉   | 18/26 [03:24<01:34, 11.80s/it]

Processing PH...
Processing PAYX...
Processing PYPL...
Processing PNR...
Processing PEP...
Processing PFE...
Processing PCG...
Processing PM...
Processing PSX...
Processing PNW...
Processing PNC...
Processing POOL...
Processing PPG...
Processing PPL...
Processing PFG...
Processing PG...
Processing PGR...
Processing PLD...
Processing PRU...
Processing PEG...

 73%|███████▎  | 19/26 [03:36<01:21, 11.68s/it]

Processing PTC...
Processing PSA...
Processing PHM...
Processing PWR...
Processing QCOM...
Processing DGX...
Processing Q...
Processing RL...
Processing RJF...
Processing RTX...
Processing O...
Processing REG...
Processing REGN...
Processing RF...
Processing RSG...
Processing RMD...
Processing RVTY...
Processing HOOD...
Processing ROK...
Processing ROL...

 77%|███████▋  | 20/26 [03:47<01:08, 11.43s/it]

Processing ROP...
Processing ROST...
Processing RCL...
Processing SPGI...
Processing CRM...
Processing SNDK...
Processing SBAC...
Processing SLB...
Processing STX...
Processing SRE...
Processing NOW...
Processing SHW...
Processing SPG...
Processing SWKS...
Processing SJM...
Processing SW...
Processing SNA...
Processing SOLV...
Processing SO...
Processing LUV...

 81%|████████  | 21/26 [03:59<00:57, 11.55s/it]

Processing SWK...
Processing SBUX...
Processing STT...
Processing STLD...
Processing STE...
Processing SYK...
Processing SMCI...
Processing SYF...
Processing SNPS...
Processing SYY...
Processing TMUS...
Processing TROW...
Processing TTWO...
Processing TPR...
Processing TRGP...
Processing TGT...
Processing TEL...
Processing TDY...
Processing TER...
Processing TSLA...

 85%|████████▍ | 22/26 [04:08<00:43, 10.92s/it]

Processing TXN...
Processing TPL...
Processing TXT...
Processing TMO...
Processing TJX...
Processing TKO...
Processing TTD...
Processing TSCO...
Processing TT...
Processing TDG...
Processing TRV...
Processing TRMB...
Processing TFC...
Processing TYL...
Processing TSN...
Processing USB...
Processing UBER...
Processing UDR...
Processing ULTA...
Processing UNP...

 88%|████████▊ | 23/26 [04:18<00:32, 10.78s/it]

Processing UAL...
Processing UPS...
Processing URI...
Processing UNH...
Processing UHS...
Processing VLO...
Processing VTR...
Processing VLTO...
Processing VRSN...
Processing VRSK...
Processing VZ...
Processing VRTX...
Processing VRT...
Processing VTRS...
Processing VICI...
Processing V...
Processing VST...
Processing VMC...
Processing WRB...
Processing GWW...

 92%|█████████▏| 24/26 [04:31<00:22, 11.32s/it]

Processing WAB...
Processing WMT...
Processing DIS...
Processing WBD...
Processing WM...
Processing WAT...
Processing WEC...
Processing WFC...
Processing WELL...
Processing WST...
Processing WDC...
Processing WY...
Processing WSM...
Processing WMB...
Processing WTW...
Processing WDAY...
Processing WYNN...
Processing XEL...
Processing XYL...
Processing YUM...

 96%|█████████▌| 25/26 [04:42<00:11, 11.16s/it]

Processing ZBRA...
Processing ZBH...
Processing ZTS...

100%|██████████| 26/26 [04:43<00:00, 10.91s/it]

In [8]:
df_sp500.to_csv("sp500_ohlcv.csv", index=False)

In [9]:
print(df_sp500.shape)
df_sp500.groupby("ticker").size().head()
df_sp500.head()

(2920545, 8)

,date,ticker,open,high,low,close,adj_close,volume
0,2000-01-03,A,46.963894,47.075713,40.180220,42.938419,42.938419,4674353
1,2000-01-04,A,40.627500,41.074778,38.614762,39.658405,39.658405,4765083
2,2000-01-05,A,39.509313,39.658406,35.968387,37.198391,37.198391,5758642
3,2000-01-06,A,36.751110,36.974749,34.663825,35.782013,35.782013,2534434
4,2000-01-07,A,35.222912,39.322934,35.185641,38.763840,38.763840,2819626

In [10]:
# check the start date and end date for these stock
date_summary = (
    df_sp500
    .groupby("ticker")["date"]
    .agg(start_date="min", end_date="max")
    .reset_index()
)

date_summary.head()

  ticker start_date   end_date
0      A 2000-01-03 2026-04-28
1   AAPL 2000-01-03 2026-04-28
2   ABBV 2013-01-02 2026-04-28
3   ABNB 2020-12-10 2026-04-28
4    ABT 2000-01-03 2026-04-28

In [ ]:
#all of the stock have the same end_date
date_summary["end_date"].nunique()

1

In [ ]:
#Check the latest start time.
date_summary["start_date"].max()

Timestamp('2025-10-27 00:00:00')

In [16]:
#Delete all stocks with a start date after 2005.
valid_tickers = date_summary[
    date_summary["start_date"] <= "2005-01-01"
]["ticker"]
df_sp500_filtered = df_sp500[
    df_sp500["ticker"].isin(valid_tickers)
]
df_sp500_filtered["ticker"].nunique()

387

In [17]:
df_sp500_filtered.to_csv("sp500_filtered.csv", index=False)